package com.afterkraft.kraftrpg.api.spells;

import com.afterkraft.kraftrpg.api.entity.Champion;

/**
 * Represents a Spell that only has results on activation through command or binding.
 * As this is an active spell that requires some possible binding/targetting, usage
 * should be included by the implementation for players to understand how to use this
 * active spell.
 *
 * Recommended use of this interface is {@link com.afterkraft.kraftrpg.api.spells.ActiveSpell}
 */
public interface Active<T extends SpellArgument> extends ISpell {

    /**
     * Returns the instructional usage for this spell, including various accepted arguments
     * handled in {@link #parse(com.afterkraft.kraftrpg.api.entity.Champion, String[])}
     * @return the instructional usage for this spell
     */
    public String getUsage();

    /**
     * Set the instructional usage for this spell
     * @param usage the instructional usage for this spell
     */
    public void setUsage(String usage);

    /**
     * The standard warmup process for an Active Spell.
     * This is called prior
     * @param champion
     */
    public void onWarmUp(Champion champion);

    /**
     * Request this spell to parse the given arguments executed by various
     * means. SpellArguments are state objects that RPGPlayers can cache for
     * binds and other possible uses.
     *
     * @param champion
     *            - The Champion to be used, this is passed solely for the
     *            benefit of the SpellArgument creation
     * @param args
     *            - Raw string arguments that are passed from any source
     * @return a new SpellArgument object generated by this Spell for this
     *         Spell's use
     */
    public T parse(Champion champion, String[] args);


    /**
     * Cast this spell according to this spell's defined SpellArgument. This can
     * be used in instances like bound spells to Items and
     *
     * @param champion
     *            - The Champion to cast this spell
     * @param argument
     *            - The SpellArgument to use this spell with
     * @return true if Spell usage was successfull
     */
    public boolean useSpell(Champion champion, T argument);

}
