/*
 * Copyright 2014 Gabriel Harris-Rouquette
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http:www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.afterkraft.kraftrpg.api.skills;


public enum SkillType {
    ABILITY_PROPERTY_AIR,
    ABILITY_PROPERTY_BLEED,
    ABILITY_PROPERTY_DARK,
    ABILITY_PROPERTY_DISEASE,
    ABILITY_PROPERTY_EARTH,
    ABILITY_PROPERTY_FIRE,
    ABILITY_PROPERTY_ICE,
    ABILITY_PROPERTY_ILLUSION,
    ABILITY_PROPERTY_LIGHT,
    ABILITY_PROPERTY_LIGHTNING,
    ABILITY_PROPERTY_MAGICAL,
    ABILITY_PROPERTY_PHYSICAL,
    ABILITY_PROPERTY_POISON,
    ABILITY_PROPERTY_PROJECTILE,
    ABILITY_PROPERTY_SONG,
    ABILITY_PROPERTY_WATER,
    AGGRESSIVE,
    AREA_OF_EFFECT,
    ARMOR_PIERCING,
    BLINDING,
    BLOCK_CREATING,
    BLOCK_REMOVING,
    BLOCK_MODIFYING,
    BUFFING,
    DAMAGING,
    DEBUFFING,
    DESUMMONING,
    DISABLE_COUNTERING,
    DISABLING,
    DISKILLING,
    DURABILITY_INCREASING,
    DURABILITY_REDUCING,
    FORCE,
    FORM_ALTERING,
    HEALING,
    HEALTH_FREEZING,
    INTERRUPTING,
    ITEM_CREATION,
    ITEM_DESTRUCTION,
    ITEM_MODIFYING,
    MANA_DECREASING,
    MANA_FREEZING,
    MANA_INCREASING,
    MAX_HEALTH_DECREASING,
    MAX_HEALTH_INCREASING,
    MAX_MANA_DECREASING,
    MAX_MANA_INCREASING,
    MAX_STAMINA_INCREASING,
    MAX_STAMINA_DECREASING,
    MOVEMENT_INCREASING,
    MOVEMENT_INCREASE_COUNTERING,
    MOVEMENT_PREVENTING,
    MOVEMENT_PREVENTION_COUNTERING,
    MOVEMENT_SLOWING,
    MOVEMENT_SLOWING_COUNTERING,
    MULTI_GRESSIVE,
    NO_SELF_TARGETTING,
    RESURRECTING,
    SILENCABLE,
    SILENCING,
    STEALTHY,
    STAMINA_DECREASING,
    STAMINA_INCREASING,
    STAMINA_FREEZING,
    STUNNING,
    SUMMONING,
    TELEPORTING,
    UNBINDABLE,
    UNINTERRUPTIBLE,
    VELOCITY_DECREASING,
    VELOCITY_INCREASING
}
